version: "2"
services:
  app:
    build: ./container
    volumes:
      - ./container/data/files:/arozos/src/files
      - ./container/data/web:/arozos/web
      - ./container/data/system:/arozos/system

    ports:
      - "8980:80"
      - "8921:21"
    restart: always
