version: "2"
services:
  app:
    build: ./container
    volumes:
      - ./container/data/files:/arozos/src/files
      - ./container/data/web:/arozos/src/web
      - ./container/data/system:/arozos/src/system

    ports:
      - "8980:8080"
    restart: always
