version: "2"
services:
  app:
    build: ./container
    volumes:
      - ./container/data/files:/arozos/files
      - ./container/data/web:/arozos/web
      - ./container/data/system:/arozos/system

    ports:
      - "8980:8080"
    restart: always
