version: "2"
services:
  app:
    build: ./container
    volumes:
      - ./container/data/files:/arozos/src/files
      - ./container/data/tmp:/arozos/src/tmp
      - ./container/data/system:/arozos/src/system
    ports:
      - "8980:80"
      - "8921:21"
    restart: always